### ISSUE TITLE
Template fields not working

### ISSUE THREAD

**Issue by krankydonkey** [bambanah/deemix#105]
I am running this in a docker container, and have logged in with my account ARL. When trying to download a playlist with the playlist track template set to: 

%artist% - %album% - %tracknumber% - %title%

The tracks are missing half their fields. For example: 

BROADHURST - %album% - %tracknumber% - Little Lover.mp3

**Comment by krankydonkey** [comment]
solved by my pull request #107

**Comment by bambanah** [comment]
Your fix has been included in the latest release ([webui@4.2.6](https://github.com/bambanah/deemix/releases/tag/deemix-webui%404.2.6), [gui@0.2.15](https://github.com/bambanah/deemix/releases/tag/deemix-gui%400.2.15)). Thanks again for the PR!

![image](https://github.com/user-attachments/assets/c621b6bd-1605-48de-81af-e386fd0cb083)

**Comment by Verkhovskyi** [comment]
@bambanah, looks like there's something missing as I can't get to work `%date%` tag for album folder template. Folders have nothing in place of `%date%`. `%year%` is working though
