### ISSUE TITLE
File type not reflected in extension

### ISSUE THREAD

**Issue by krankydonkey** [bambanah/deemix#106]
I am running this in a docker container, and have logged in with my account ARL. I have set the quality profile to FLAC, however, all songs I download have a ".mp3" extension. I changed the quality to MP3 320kbps and the downloaded file is much smaller, so it looks like its downloading the FLAC file correctly, just not naming it as such.

**Comment by krankydonkey** [comment]
solved by my pull request #107

**Comment by bambanah** [comment]
This has been resolved in the latest release ([webui@4.2.6](https://github.com/bambanah/deemix/releases/tag/deemix-webui%404.2.6), [gui@0.2.15](https://github.com/bambanah/deemix/releases/tag/deemix-gui%400.2.15)). Thanks again for the PR!
