### ISSUE TITLE
Corrupt MP3 @ 320kbps

### ISSUE THREAD

**Issue by AjayiDublin** [bambanah/deemix#108]
<img width="981" alt="Screenshot 2024-09-21 at 11 07 52 PM" src="https://github.com/user-attachments/assets/4656df1e-cf78-4911-9067-3a365ea41bf6">

Moving to this version of Deemix from the original. Previously songs would import into Serato without any problems. Noticing audio artifacts, audio skipping and Serato reporting 80-90% of imported songs as corrupt.

Premium Deezer account is being used.

All the best.

**Comment by de-rancho** [comment]
I second this for flac and recordbox. The stream seems to be corrupted
![image](https://github.com/user-attachments/assets/d9bbd909-c42f-463e-815a-16ad7b9ad957)

**Comment by krankydonkey** [comment]
Ive encountered this problem too, when playing in vlc most of the tracks have stutters every 10-20s

**Comment by bambanah** [comment]
Sorry for the delay, should be solved by #110. Will be in the next release.
