### ISSUE TITLE
Account not being recognised as Hi-Fi

### ISSUE THREAD

**Issue by martin-77** [bambanah/deemix#130]
Premium Account on Deezer, but Flac is grayed out

![Bildschirmfoto 2024-10-28 um 08 49 27](https://github.com/user-attachments/assets/50e2f333-65f4-42b0-8c3e-36348ba13fab)
![Bildschirmfoto 2024-10-28 um 08 50 23](https://github.com/user-attachments/assets/e01159b6-9b58-4627-831c-7757bda2a9b9)

Enviroment: Running self compiled Version on Debian

**Comment by bambanah** [comment]
What's your internet speed? After Deezer authentication, Deezer itself will decide whether your device can stream lossless or not, and as far as I'm aware deemix doesn't have much control over that. From what I can [find online](https://support.deezer.com/hc/en-gb/articles/115004588345-High-Fidelity-HiFi-on-Deezer), Hi-Fi requires a network speed of >5 Mbps.

Another suggestion would be to try reauthenticating or play around with your settings on Deezer if that doesn't work.

When Deezer reports that your account can stream lossless, deemix will display "Hi-Fi" under your account name.

![image](https://github.com/user-attachments/assets/9ac7acd3-ee10-47c4-bbf7-065c1651088c)

**Comment by martin-77** [comment]
solved by version 0.33 or was a temporary issue with deezer.
