### ISSUE TITLE
GUI Not Starting on Windows 11

### ISSUE THREAD

**Issue by 3bagorion33** [bambanah/deemix#131]
I'm trying to run the latest release on Windows 11. I downloaded the installer from the repository, ran it. The application window pops up for 1 second and then dies. Nothing hangs in processes, no logs (or I didn't understand where to look for them).

**Comment by bambanah** [comment]
Can you try running version 0.3.3? It should fix your issue (working now on my windows machine)

**Comment by 3bagorion33** [comment]
Yeah, it's working fine now.
