### ISSUE TITLE
js/bundle.js isn't loading correctly on WebUI

### ISSUE THREAD

**Issue by 3bagorion33** [bambanah/deemix#132]
**To Reproduce**
1. Install on the host `docker pull ghcr.io/bambanah/deemix:v4.2.8`
2. Run on the host ```
docker run -d --name Deemix \
  -v /path/to/music:/downloads \
  -v /path/to/config:/config \
  -p 6595:6595 \
  ghcr.io/bambanah/deemix:latest```
3. Open remote client http://my_address:6599 (remapped port by unix)

> If you're reading this it means that js/bundle.js isn't loading correctly.
> Make sure the file is present, if not build the webui.

**Comment by 3bagorion33** [comment]
After reloading page seems all ok 🤔

**Comment by martin-77** [comment]
Please close your issue if your  problem is solved
